from my_project.terminals.domain.alert import Alert
from my_project.terminals.domain.battery_status import BatteryStatus
from my_project.terminals.domain.incident_report import IncidentReport
from my_project.terminals.domain.maintenance import Maintenance
from my_project.terminals.domain.robot import Robot
from my_project.terminals.domain.robot_control import RobotControl
from my_project.terminals.domain.robot_zone import RobotZone
from my_project.terminals.domain.sensor import Sensor
from my_project.terminals.domain.user import User
from my_project.terminals.domain.zone import Zone
from my_project.terminals.dao.orders.alert_dao import AlertDAO
from my_project.terminals.dao.orders.battery_status_dao import BatteryStatusDAO
from my_project.terminals.dao.orders.incident_report_dao import IncidentReportDAO
from my_project.terminals.dao.orders.maintenance_dao import MaintenanceDAO
from my_project.terminals.dao.orders.robot_dao import RobotDAO
from my_project.terminals.dao.orders.robot_control_dao import RobotControlDAO
from my_project.terminals.dao.orders.robot_zone_dao import RobotZoneDAO
from my_project.terminals.dao.orders.sensor_dao import SensorDAO
from my_project.terminals.dao.orders.user_dao import UserDAO
from my_project.terminals.dao.orders.zone_dao import ZoneDAO